defaultBaseImage: gcr.io/distroless/static-debian11

builds:
- id: falco-talon
  dir: .
  main: .
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
