listenAddress: "0.0.0.0"
listenPort: "2803"
rulesFile: "./rules.yaml"
kubeConfig: "~/.kube/config"

defaultNotifiers:
  - slack

notifiers:
  slack:
    webhookurl: "https://hooks.slack.com/services/XXXX"
    # icon: ""
    # username: ""
    footer: ""
    format: short
  email:
    smtpserver: ""
    user: ""
    password: ""
    from: ""
    to: ""
  webhook:
    url: ""