listenAddress: "0.0.0.0" # default: "0.0.0.0"
listenPort: "2803" # default: "2803"
rulesFile: "./rules.yaml" # default: "./rules.yaml"
# kubeConfig: "~/.kube/config" # ony if Falco Talon is running outside Kubernetes

defaultNotifiers: # this notifiers will be enabled for all rules
  - slack

notifiers:
  slack:
    webhookurl: "https://hooks.slack.com/services/XXXX"
    # icon: "" # default: "https://upload.wikimedia.org/wikipedia/commons/2/26/Circaetus_gallicus_claw.jpg"
    # username: "" # default: "Falco Talon"
    footer: "" # default: "https://github.com/Issif/falco-talon"
    format: long # default: long
  # webhook:
  #   url: ""