listen_address: "0.0.0.0" # default: "0.0.0.0"
listen_port: "2803" # default: "2803"
rules_file: "./rules.yaml" # default: "./rules.yaml"
# kubeConfig: "~/.kube/config" # only if Falco Talon is running outside Kubernetes
log_format: "color" # log Format: text, color, json (default: color)
watch_rules: true # reload if the rules file changes (default: true)
print_all_events: true # print in logs all received events, not only those which match

deduplication_leader_lease: true # in k8s only, create a lease for the leader election
deduplication_time_window_seconds: 5 # duration in seconds for the deduplication time window

default_notifiers: # these notifiers will be enabled for all rules
  - k8sevents

aws:
#  region: us-east-1 # if not specified, default region from provider credential chain will be used
#  access_key: a9s01m1mdlaklska # if not specified, default access_key from provider credential chain will be used
#  secret_key: my_super_secret # if not specified, default secret_key from provider credential chain will be used

notifiers:
  slack:
    webhook_url: "https://hooks.slack.com/services/XXXX"
    # icon: "" # default: "https://upload.wikimedia.org/wikipedia/commons/2/26/Circaetus_gallicus_claw.jpg"
    # username: "" # default: "Falco Talon"
    footer: "" # default: "https://github.com/Falco-Talon/falco-talon"
    format: long # default: long
  # webhook:
  #   url: ""
  # smtp:
  #   host_port: ""
  #   from: ""
  #   to: ""
  #   user: ""
  #   password: ""
  #   format: "html"