---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - update
      - patch
      - delete
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - delete
  - apiGroups:
      - networking.k8s.io
      - projectcalico.org
    resources:
      - networkpolicies
      - caliconetworkpolicies
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
    verbs:
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - namespace
    verbs:
      - get
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - create
      - update
      - patch
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - {{ template "falco-talon.name" . }}
  verbs:
    - use
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "falco-talon.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}