---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  {{- if .Values.rbac.namespaces }}
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: {{ .Values.rbac.namespaces }}
  {{- end }}
  {{- if .Values.rbac.pods }}
  - apiGroups:
      - ""
    resources:
      - pods
    verbs: {{ .Values.rbac.pods }}
  {{- end }}
  {{- if .Values.rbac.nodes }}
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs: {{ .Values.rbac.nodes }}
  {{- end }}
  {{- if .Values.rbac.podsExec }}
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs: {{ .Values.rbac.podsExec }}
  {{- end }}
  {{- if .Values.rbac.podsEviction }}
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs: {{ .Values.rbac.podsEviction }}
  {{- end }}
  {{- if .Values.rbac.events }}
  - apiGroups:
      - ""
    resources:
      - events
    verbs: {{ .Values.rbac.events }}
  {{- end }}
  {{- if .Values.rbac.daemonsets }}
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
    verbs: {{ .Values.rbac.daemonsets }}
  {{- end }}
  {{- if .Values.rbac.deployments }}
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs: {{ .Values.rbac.deployments }}
  {{- end }}
  {{- if .Values.rbac.replicasets }}
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs: {{ .Values.rbac.replicasets }}
  {{- end }}
  {{- if .Values.rbac.statefulsets }}
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs: {{ .Values.rbac.statefulsets }}
  {{- end }}
  {{- if .Values.rbac.networkpolicies }}
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs: {{ .Values.rbac.networkpolicies }}
  {{- end }}
  {{- if .Values.rbac.caliconetworkpolicies }}
  - apiGroups:
      - "projectcalico.org"
    resources:
      - caliconetworkpolicies
    verbs: {{ .Values.rbac.caliconetworkpolicies }}
  {{- end }}
  {{- if .Values.rbac.ciliumnetworkpolicies }}
  - apiGroups:
      - "cilium.io"
    resources:
      - ciliumnetworkpolicies
    verbs: {{ .Values.rbac.ciliumnetworkpolicies }}
  {{- end }}
  {{- if .Values.rbac.roles }}
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
    verbs: {{ .Values.rbac.roles }}
  {{- end }}
  {{- if .Values.rbac.clusterroles }}
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
    verbs: {{ .Values.rbac.clusterroles }}
  {{- end }}
  {{- if .Values.rbac.configmaps }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: {{ .Values.rbac.configmaps }}
  {{- end }}
  {{- if .Values.rbac.secrets }}
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: {{ .Values.rbac.secrets }}
  {{- end }}
  {{- if .Values.rbac.leases }}
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs: {{ .Values.rbac.leases }}
  {{- end }}
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - {{ template "falco-talon.name" . }}
  verbs:
    - use
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falco-talon.name" . }}
    helm.sh/chart: {{ include "falco-talon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "falco-talon.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "falco-talon.name" . }}
  namespace: {{ .Release.Namespace }}