apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falco-talon.name" . }}-config
stringData:
  config.yaml: |
    rulesFile: "/etc/rules/rules.yaml"
    watchRules: {{ default true .Values.watchRules }}
    defaultNotifiers: 
    {{- range .Values.defaultNotifiers }}
      - {{ . -}}
    {{ end }}
    notifiers:
    {{- toYaml .Values.notifiers | nindent 6 }}
