version: "3"

volumes:
  postgres_data:
services:

  # open telemetry collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.72.0
    command: ["--config=/otel/collector-config.yaml"]
    volumes:
      - ./otel/collector-config.yaml:/otel/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme123
    ports:
      - "9000:9000"
      - "9001:9001"