- name: Rule Labelize
  match:
    priority: "<Critical"
  action:
    name: kubernetes:labelize
    arguments:
      suspicious: "true"
      run: ""
- name: Rule Terminate
  match:
    rules:
      - Terminal shell in container
  action:
    name: kubernetes:terminate
    parameters:
      gracePeriodSeconds: 0