- action: Terminate Pod
  actionner: kubernetes:terminate

- action: Disable outbound connections with Calico
  actionner: calico:networkpolicy

- action: Labelize Pod as Suspicious
  actionner: kubernetes:labelize
  parameters:
    labels:
      suspicious: true

- rule: Suspicious outbound connection
  match:
    rules:
      - Unexpected outbound connection destination
      - Outbound Connection to Free.fr
  actions:
    - action: Disable outbound connections with Calico

- rule: Terminal shell in container 
  match:
    rules:
      - Terminal shell in container
    output_fields:
      - k8s.ns.name!=kube-system, k8s.ns.name!=falco
  actions:
    - action: Labelize Pod as Suspicious
