name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    needs: lint
    uses: ./.github/workflows/test.yml
  main:
    needs: [lint, test]
    strategy:
      matrix:
        go-version: [1.22.x]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        install-only: true

    - name: Install ko
      uses: ko-build/setup-ko@v0.6

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push images to Dockerhub
    - name: Run Mage
      uses: magefile/mage-action@v3
      with:
        version: latest
        args: push:images

    # Push images to AWS Public ECR (TODO: move into to the mage file)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: arn:aws:iam::292999226676:role/github_actions-falco-talon-ecr
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        registry-type: public

    - run: |
        docker push public.ecr.aws/falcosecurity/falco-talon:latest-amd64
        docker push public.ecr.aws/falcosecurity/falco-talon:latest-arm64
        docker push public.ecr.aws/falcosecurity/falco-talon:latest-armv7
        docker manifest create --amend public.ecr.aws/falcosecurity/falco-talon:latest public.ecr.aws/falcosecurity/falco-talon:latest-amd64 \
          public.ecr.aws/falcosecurity/falco-talon:latest-arm64 public.ecr.aws/falcosecurity/falco-talon:latest-armv7
        docker manifest push --purge public.ecr.aws/falcosecurity/falco-talon:latest