name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    needs: lint
    uses: ./.github/workflows/test.yml
  main:
    needs: [lint, test]
    strategy:
      matrix:
        go-version: [1.22.x]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        install-only: true

    - name: Install ko
      uses: ko-build/setup-ko@v0.6

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Mage
      uses: magefile/mage-action@v3
      with:
        version: latest
        args: pushimages