name: Build

on:
  push:
    tags:
      - "*"

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing

jobs:
  release:
    strategy:
      matrix:
        go-version: [1.19.x]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        install-only: true
        
    - name: Run Mage
      uses: magefile/mage-action@v2
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push images to Dockerhub
      run: |
        docker manifest push --purge issif/falco-talon:latest