name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run Mage
      uses: magefile/mage-action@v3
      with:
        version: latest
        args: test
